$axure.loadCurrentPage({
  "url":"增值扩充服务收费项目.html",
  "generationDate":new Date(1509955837081.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bbf82746c2c4d02bf4d15f95f50c7f7",
    "type":"Axure:Page",
    "name":"增值扩充服务收费项目",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"416a174c053a45fe99cf1e809ac02577",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":360,
              "height":422}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbeb1200d693472a9a845d10b4a757a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":360,
                  "height":422}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"685050d1951e472a9f1a3783d6cac88f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":20},
            "size":{
              "width":371,
              "height":422}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa26e459a0e940199a194c9419141744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":20},
                "size":{
                  "width":371,
                  "height":422}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增值扩充服务收费项目/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "416a174c053a45fe99cf1e809ac02577":{
      "scriptId":"u0"},
    "fbeb1200d693472a9a845d10b4a757a1":{
      "scriptId":"u1"},
    "685050d1951e472a9f1a3783d6cac88f":{
      "scriptId":"u2"},
    "fa26e459a0e940199a194c9419141744":{
      "scriptId":"u3"}}});