$axure.loadCurrentPage({
  "url":"收益渠道.html",
  "generationDate":new Date(1509955837124.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0490678e4e24437eb488f0a8872337c3",
    "type":"Axure:Page",
    "name":"收益渠道",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f1c430e4d8cc4bc5895b49fcb53dde0b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":300},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760f424c38e6493093de3aa2b4ba5645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":300},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"8e8ca8bbbb75410b9164425993c46a8e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":30},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c8e44744aca4c67a1c50d63893e3426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":30},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"0f1f4b36a5b04fd59eaf48727dbd6103",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":307},
            "size":{
              "width":360,
              "height":303}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff972f30f32464c9945db2fcacd3ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":307},
                "size":{
                  "width":360,
                  "height":303}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收益渠道/u4.png"}},
{
          "id":"8c50470f3e90408d852ba57feb6bd038",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":427},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8f04d036a74949a7cb9eb364a6a485",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":427},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"51413d056ea3447fbdc5bcbb9c946ef0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":18},
            "size":{
              "width":424,
              "height":239}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb2bd5aeb3604e71ab00f12e84ef4dcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":18},
                "size":{
                  "width":424,
                  "height":239}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收益渠道/u8.jpg"}},
{
          "id":"4624c87a44444ee3a37f8f6f765b614d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":130},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd51c384c7f4395920fdb3c8e2257bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":130},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"37bd3bd2bc52455481eac256950fb5c8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":200},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a87bcb729c4943899d332d8adf277591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":200},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"bbec202560634473aecdb8555538aaef",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":130},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2509e02f9154c1880c0d4bd76e864e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":130},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f1c430e4d8cc4bc5895b49fcb53dde0b":{
      "scriptId":"u0"},
    "760f424c38e6493093de3aa2b4ba5645":{
      "scriptId":"u1"},
    "8e8ca8bbbb75410b9164425993c46a8e":{
      "scriptId":"u2"},
    "7c8e44744aca4c67a1c50d63893e3426":{
      "scriptId":"u3"},
    "0f1f4b36a5b04fd59eaf48727dbd6103":{
      "scriptId":"u4"},
    "aff972f30f32464c9945db2fcacd3ea4":{
      "scriptId":"u5"},
    "8c50470f3e90408d852ba57feb6bd038":{
      "scriptId":"u6"},
    "bf8f04d036a74949a7cb9eb364a6a485":{
      "scriptId":"u7"},
    "51413d056ea3447fbdc5bcbb9c946ef0":{
      "scriptId":"u8"},
    "fb2bd5aeb3604e71ab00f12e84ef4dcf":{
      "scriptId":"u9"},
    "4624c87a44444ee3a37f8f6f765b614d":{
      "scriptId":"u10"},
    "6bd51c384c7f4395920fdb3c8e2257bf":{
      "scriptId":"u11"},
    "37bd3bd2bc52455481eac256950fb5c8":{
      "scriptId":"u12"},
    "a87bcb729c4943899d332d8adf277591":{
      "scriptId":"u13"},
    "bbec202560634473aecdb8555538aaef":{
      "scriptId":"u14"},
    "a2509e02f9154c1880c0d4bd76e864e1":{
      "scriptId":"u15"}}});