$axure.loadCurrentPage({
  "url":"主结构.html",
  "generationDate":new Date(1509955837195.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7af4f15c72224943bc402b20abc22c35",
    "type":"Axure:Page",
    "name":"主结构",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1801a011978e411d95727843b8f34052",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":30},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2784469e91408a9e811a8aa217194c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":30},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"cb516a46d7744a00a925387ef942183d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":150},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24f0da2e118e410d87e5c070d38e786d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":150},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"8a5de069ee324abba47b214e3a5c345b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":150},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253a4eb6a4e34e278ed0a3ad540da564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":150},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"6c791f4bcb734c899dc6eeb564e0cdfe",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":400},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a89cd018524f48eba1a69e9d85b68091",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":400},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"29aab982771f412caf1132531d1c4ee0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":280},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d696ce295e194b8ab3cfc9e440c53fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":280},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"83ba5eafd8ec41f587bb070b3caf76b6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":280},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b577fceb84e46709fbabb1d40b44ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":280},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"4aa77e1225a44498b39e3bd4ac2dc99f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aea5f0bffc1d436ab47443cb070dd2ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":90},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"d3fd8123a0ba41beaa818c684469aec4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8954f2a192bd4f05aef064a7104f6dd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":90},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"e9701845fa7b48cdbb7347ac6c7aa8a6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":190,
              "y":210},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b070b7ac8d4dcb9f1f3adfd1489c25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":210},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"616069b294e949e1860a9ae3f47cbbf2",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":210},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8aa335043f42069fa2655771c9c50a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":210},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"58ebe8d12ee1401cab80f3885640d01e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":110,
              "y":340},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d62d1de782440b0969486dbd97c34fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":340},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"ae37d5d23b684787ab5c08644a0e4f62",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":270,
              "y":340},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7554a2bc814744a68f7cc6deb5a1eb28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":340},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"215f13c72c6d45c4b0dbce16772565de",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":420,
              "y":210},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a42b30770f54856a4c23a9589ce1a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":210},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "1801a011978e411d95727843b8f34052":{
      "scriptId":"u0"},
    "fa2784469e91408a9e811a8aa217194c":{
      "scriptId":"u1"},
    "cb516a46d7744a00a925387ef942183d":{
      "scriptId":"u2"},
    "24f0da2e118e410d87e5c070d38e786d":{
      "scriptId":"u3"},
    "8a5de069ee324abba47b214e3a5c345b":{
      "scriptId":"u4"},
    "253a4eb6a4e34e278ed0a3ad540da564":{
      "scriptId":"u5"},
    "6c791f4bcb734c899dc6eeb564e0cdfe":{
      "scriptId":"u6"},
    "a89cd018524f48eba1a69e9d85b68091":{
      "scriptId":"u7"},
    "29aab982771f412caf1132531d1c4ee0":{
      "scriptId":"u8"},
    "d696ce295e194b8ab3cfc9e440c53fb2":{
      "scriptId":"u9"},
    "83ba5eafd8ec41f587bb070b3caf76b6":{
      "scriptId":"u10"},
    "0b577fceb84e46709fbabb1d40b44ca9":{
      "scriptId":"u11"},
    "4aa77e1225a44498b39e3bd4ac2dc99f":{
      "scriptId":"u12"},
    "aea5f0bffc1d436ab47443cb070dd2ed":{
      "scriptId":"u13"},
    "d3fd8123a0ba41beaa818c684469aec4":{
      "scriptId":"u14"},
    "8954f2a192bd4f05aef064a7104f6dd2":{
      "scriptId":"u15"},
    "e9701845fa7b48cdbb7347ac6c7aa8a6":{
      "scriptId":"u16"},
    "b8b070b7ac8d4dcb9f1f3adfd1489c25":{
      "scriptId":"u17"},
    "616069b294e949e1860a9ae3f47cbbf2":{
      "scriptId":"u18"},
    "1c8aa335043f42069fa2655771c9c50a":{
      "scriptId":"u19"},
    "58ebe8d12ee1401cab80f3885640d01e":{
      "scriptId":"u20"},
    "0d62d1de782440b0969486dbd97c34fe":{
      "scriptId":"u21"},
    "ae37d5d23b684787ab5c08644a0e4f62":{
      "scriptId":"u22"},
    "7554a2bc814744a68f7cc6deb5a1eb28":{
      "scriptId":"u23"},
    "215f13c72c6d45c4b0dbce16772565de":{
      "scriptId":"u24"},
    "9a42b30770f54856a4c23a9589ce1a17":{
      "scriptId":"u25"}}});