$axure.loadCurrentPage({
  "url":"怪物.html",
  "generationDate":new Date(1509955837465.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3fc388dff9284e2d9723d00a9914f531",
    "type":"Axure:Page",
    "name":"怪物",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ff33d02b53541a686f5b363d31e9eb0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":335},
            "size":{
              "width":200,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eec37ec32f4b4ec39ac0e8ac9a943024",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":335},
                "size":{
                  "width":200,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u0.png"}},
{
          "id":"88368ebca0a04c80a76722b3f0728901",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":453,
              "y":349},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3cac5614794424492dfdad93d101bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":453,
                  "y":349},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5da04d9d5969416b95b19e0a06e96221",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":320},
            "size":{
              "width":200,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb70aa233fb45b7a96e84229a75528f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":320},
                "size":{
                  "width":200,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u0.png"}},
{
          "id":"e0d19d054d8c424fb8690cc4518aec0b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d145ea326e24bb3a16b28429988a61b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":40},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"864c725e5e514b378022a5658b0ebab2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":180},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c4b358150174c1db3d645ad9ed3be2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":180},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"b2ae664e788e47c8a6fc39370a8793ee",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":405},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"184b2ffc26bd4d9ab835010216a030dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":405},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"77fd22555e4d4ed19920c45b107652c1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":390},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243f9e511198414e99866edb0556efaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":390},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"8c4b7dad261c47f89d64b41bf3cb7722",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":320,
              "y":100},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43f5dec6bf849419dbba74e2c7f941f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":100},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"0aca47746a9a4508a4bd318b3cd487d3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":320,
              "y":240},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca5d7073fee42068ca8aea1f4b9994c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":240},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"4e60bd3f11b84280bbd4754fcba41c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":123,
              "y":334},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"893337047e174597be8a703353708ff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":123,
                  "y":334},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7734a2a7532a44eeb6db7dfe970183d8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":320,
              "y":240},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4dbab40c4184dc7a2a12c1bcdbe00cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":240},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"497a7c828a6445e28b88bc3de468da07",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":205,
              "y":420},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca0bea93c044a13a130b6ae613145fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":420},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"6ce88408a6024ffa861c8aa0300f4e6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":44},
            "size":{
              "width":76,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7679f47ef4c7459eb780abf9e38ee5da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":44},
                "size":{
                  "width":76,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u24.gif"}},
{
          "id":"4e501f6a760a44f5a42081ed985c55f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":44},
            "size":{
              "width":76,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3efe6c66c0db40d6bf9fd3c4e816edc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":44},
                "size":{
                  "width":76,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u26.gif"}},
{
          "id":"99e48f17f6214b439a6e1f8a24c11cdc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":44},
            "size":{
              "width":104,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49ed28eae38458985b04c663f9e0243",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":44},
                "size":{
                  "width":104,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u28.gif"}},
{
          "id":"46c7c6dba1804a8db06e38198a5e64a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":220,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49edd906eea6409c8dfe47d53f5b17a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":20,
                  "y":40},
                "size":{
                  "width":220,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75fb366b1fa84fe58f8d6c1bbe6080e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":710,
              "y":40},
            "size":{
              "width":135,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85efff76306843a491dbfca20d1974b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":40},
                "size":{
                  "width":135,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fd4cb94c02a43409055c257dfcf045e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66.5,
              "y":969.999938964844},
            "size":{
              "width":368,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee60e4324f04e57b7eea33663288c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66.5,
                  "y":969.999938964844},
                "size":{
                  "width":368,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u34.png"}},
{
          "id":"5f06033aedb64e85a0e1916166ea8c37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":72.5,
              "y":1238},
            "size":{
              "width":357,
              "height":347}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f08d910178054673b7fa7f78de6f7c02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72.5,
                  "y":1238},
                "size":{
                  "width":357,
                  "height":347}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u36.png"}},
{
          "id":"e9b6a72a7246431dbc4b4b3869dd1889",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":464.5,
              "y":969.999938964844},
            "size":{
              "width":351,
              "height":461}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b5a3d28f824420b16a69d707d41e54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464.5,
                  "y":969.999938964844},
                "size":{
                  "width":351,
                  "height":461}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u38.png"}},
{
          "id":"daa98ec2df054b67ba46684b27772885",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":147,
              "y":550},
            "size":{
              "width":371,
              "height":359}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cbe95f307414761b54acf78dd9491b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":147,
                  "y":550},
                "size":{
                  "width":371,
                  "height":359}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/怪物/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8ff33d02b53541a686f5b363d31e9eb0":{
      "scriptId":"u0"},
    "eec37ec32f4b4ec39ac0e8ac9a943024":{
      "scriptId":"u1"},
    "88368ebca0a04c80a76722b3f0728901":{
      "scriptId":"u2"},
    "a3cac5614794424492dfdad93d101bd8":{
      "scriptId":"u3"},
    "5da04d9d5969416b95b19e0a06e96221":{
      "scriptId":"u4"},
    "7eb70aa233fb45b7a96e84229a75528f":{
      "scriptId":"u5"},
    "e0d19d054d8c424fb8690cc4518aec0b":{
      "scriptId":"u6"},
    "1d145ea326e24bb3a16b28429988a61b":{
      "scriptId":"u7"},
    "864c725e5e514b378022a5658b0ebab2":{
      "scriptId":"u8"},
    "2c4b358150174c1db3d645ad9ed3be2c":{
      "scriptId":"u9"},
    "b2ae664e788e47c8a6fc39370a8793ee":{
      "scriptId":"u10"},
    "184b2ffc26bd4d9ab835010216a030dc":{
      "scriptId":"u11"},
    "77fd22555e4d4ed19920c45b107652c1":{
      "scriptId":"u12"},
    "243f9e511198414e99866edb0556efaf":{
      "scriptId":"u13"},
    "8c4b7dad261c47f89d64b41bf3cb7722":{
      "scriptId":"u14"},
    "c43f5dec6bf849419dbba74e2c7f941f":{
      "scriptId":"u15"},
    "0aca47746a9a4508a4bd318b3cd487d3":{
      "scriptId":"u16"},
    "cca5d7073fee42068ca8aea1f4b9994c":{
      "scriptId":"u17"},
    "4e60bd3f11b84280bbd4754fcba41c15":{
      "scriptId":"u18"},
    "893337047e174597be8a703353708ff0":{
      "scriptId":"u19"},
    "7734a2a7532a44eeb6db7dfe970183d8":{
      "scriptId":"u20"},
    "e4dbab40c4184dc7a2a12c1bcdbe00cc":{
      "scriptId":"u21"},
    "497a7c828a6445e28b88bc3de468da07":{
      "scriptId":"u22"},
    "8ca0bea93c044a13a130b6ae613145fc":{
      "scriptId":"u23"},
    "6ce88408a6024ffa861c8aa0300f4e6a":{
      "scriptId":"u24"},
    "7679f47ef4c7459eb780abf9e38ee5da":{
      "scriptId":"u25"},
    "4e501f6a760a44f5a42081ed985c55f5":{
      "scriptId":"u26"},
    "3efe6c66c0db40d6bf9fd3c4e816edc0":{
      "scriptId":"u27"},
    "99e48f17f6214b439a6e1f8a24c11cdc":{
      "scriptId":"u28"},
    "c49ed28eae38458985b04c663f9e0243":{
      "scriptId":"u29"},
    "46c7c6dba1804a8db06e38198a5e64a0":{
      "scriptId":"u30"},
    "49edd906eea6409c8dfe47d53f5b17a9":{
      "scriptId":"u31"},
    "75fb366b1fa84fe58f8d6c1bbe6080e7":{
      "scriptId":"u32"},
    "85efff76306843a491dbfca20d1974b8":{
      "scriptId":"u33"},
    "7fd4cb94c02a43409055c257dfcf045e":{
      "scriptId":"u34"},
    "6ee60e4324f04e57b7eea33663288c2f":{
      "scriptId":"u35"},
    "5f06033aedb64e85a0e1916166ea8c37":{
      "scriptId":"u36"},
    "f08d910178054673b7fa7f78de6f7c02":{
      "scriptId":"u37"},
    "e9b6a72a7246431dbc4b4b3869dd1889":{
      "scriptId":"u38"},
    "a4b5a3d28f824420b16a69d707d41e54":{
      "scriptId":"u39"},
    "daa98ec2df054b67ba46684b27772885":{
      "scriptId":"u40"},
    "0cbe95f307414761b54acf78dd9491b8":{
      "scriptId":"u41"}}});