$axure.loadCurrentPage({
  "url":"资源主要产耗、用途.html",
  "generationDate":new Date(1509955837048.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ebdb867f1ec94eb19716d802bf8cc09a",
    "type":"Axure:Page",
    "name":"资源主要产耗、用途",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"acf3766b80c24dc495dc7abd187ffb2a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":307},
            "size":{
              "width":740,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13037d4bc89d48518432bd3f6bcd0edd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":307},
                "size":{
                  "width":740,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u0.png"}},
{
          "id":"436004daff634579b2d048778fd19d9f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":504},
            "size":{
              "width":740,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65c9151a4ac14a2b859aa711b1f8e420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":504},
                "size":{
                  "width":740,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u0.png"}},
{
          "id":"405f36e3e3934c7f9799591af6870fb9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":111},
            "size":{
              "width":740,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca49ebced9a44f7a906bcb9c8c6e6e78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":111},
                "size":{
                  "width":740,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u0.png"}},
{
          "id":"474c31905c124ffda00d125cdc0b60f2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":170},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80dbc8a7fb1747dc83556d08892cc1f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":170},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u6.png"}},
{
          "id":"71cce88c3baa4cabb51df3dd81b0d4a7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":365},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0105f462cff4a75b7e557f4d59b0a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":365},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u6.png"}},
{
          "id":"7574fd5f5705490aa444851a81902890",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "location":{
              "x":270,
              "y":137},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0ef121a70344808a638c1da4f96098",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "location":{
                  "x":270,
                  "y":137},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u10.png"}},
{
          "id":"b154c621a2834d30915bc2bf679ce871",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC3300},
            "location":{
              "x":270,
              "y":217},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496b2e7a0a3c46c2bcdca63ad72c4662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC3300},
                "location":{
                  "x":270,
                  "y":217},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u12.png"}},
{
          "id":"4dbd8557960e4e399d0e581d6e12de7d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "location":{
              "x":270,
              "y":330},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59890839b2a946848357884092ca8a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "location":{
                  "x":270,
                  "y":330},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u10.png"}},
{
          "id":"45f88b16b3b94b52a8611ec46d0d18f3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC3300},
            "location":{
              "x":270,
              "y":410},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f725d6adf154114b55b6c646fba9f68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC3300},
                "location":{
                  "x":270,
                  "y":410},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u12.png"}},
{
          "id":"3bf4e66548a548659ee257bbc958c6e6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":562},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9db6a54a592d42b8852a76bf1781c8d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":562},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u6.png"}},
{
          "id":"ca96f6011eb44297a527fa8446b30067",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "location":{
              "x":270,
              "y":527},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5433442ca8ea468ebb783f01f0c52eb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "location":{
                  "x":270,
                  "y":527},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u10.png"}},
{
          "id":"68c46f893bf6431aae315056200f2652",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC3300},
            "location":{
              "x":270,
              "y":607},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"318d86b8bf00468e96f0f35845dafcdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC3300},
                "location":{
                  "x":270,
                  "y":607},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u12.png"}},
{
          "id":"c9c12aa082ef4c699be0d05424072217",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":16},
            "size":{
              "width":550,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b660b88e36442c88375fca8761f54bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":80,
                  "y":16},
                "size":{
                  "width":550,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ccba779a1f748f6bc5ea5a08a6ad4f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":137},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7bb7af209da4564b8ce3d19bb947158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":137},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u26.png"}},
{
          "id":"d5d2e43227a0482998a4c13b35ab2b25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":330},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eabbc4bfcb14ff6877c9ab997c913c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":330},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u28.png"}},
{
          "id":"4d4c4a335d8b4002811fa114b2f3d890",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":527},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7418c32da104268bd912a8f44784cac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":527},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u30.png"}},
{
          "id":"73bb856d9f9745b6b453b6fc6a7dcbc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":141,
              "y":137},
            "size":{
              "width":116,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0759d276180740619e34bffe186a9ebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":141,
                  "y":137},
                "size":{
                  "width":116,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53879477d7bd40e38301ce47f0e2f6c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":141,
              "y":330},
            "size":{
              "width":116,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7056e6597e394d14ba25205e93c1138e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":141,
                  "y":330},
                "size":{
                  "width":116,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"033db6a80c284beab561fa8b57d4b74f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":141,
              "y":527},
            "size":{
              "width":116,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8ae8a3d368448d899e252bfb65a7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":141,
                  "y":527},
                "size":{
                  "width":116,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe8be7c9290a4a20aa257c07afa8f19b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":704},
            "size":{
              "width":740,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2af530231ee8450daac2aff3a88d4e84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":704},
                "size":{
                  "width":740,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u0.png"}},
{
          "id":"5b9df5cd03494a3ab7ecc9e80a7d11f2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":762},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92647ae90d9c49b694390463f5b8c3eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":762},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u6.png"}},
{
          "id":"86be97f343fa411f96a490261a8b6621",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "location":{
              "x":270,
              "y":727},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"378764eb26ef4929962eb8606593848e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "location":{
                  "x":270,
                  "y":727},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u10.png"}},
{
          "id":"a8412d5e393b4f2d9b68e722834dc220",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC3300},
            "location":{
              "x":270,
              "y":807},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4926243c6110421cba28ac26aaa2e10d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC3300},
                "location":{
                  "x":270,
                  "y":807},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u12.png"}},
{
          "id":"71b4eb547c5e453a8eb7f1d27a858998",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":141,
              "y":727},
            "size":{
              "width":116,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9095ed6580af47ee8d4a319569490dfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":141,
                  "y":727},
                "size":{
                  "width":116,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c8a78d4cd8f43a280f7930670626902",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":727},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ddce926cfe14270a733013d44d93f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":727},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u48.png"}},
{
          "id":"49038e8c65934d9ab95e633e9c166168",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":904},
            "size":{
              "width":740,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d881ab948984838a5f307f8c3e97fff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":904},
                "size":{
                  "width":740,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u0.png"}},
{
          "id":"9515abc941674be594cb52b4a92cb48e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":962},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b820a64220472abc439b73628d5efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":962},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u6.png"}},
{
          "id":"8fe9a565174e494f95f7c104caf294a3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009900},
            "location":{
              "x":270,
              "y":927},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375c908c76c046389dd3a630cd0f9001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009900},
                "location":{
                  "x":270,
                  "y":927},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u10.png"}},
{
          "id":"16e20eaacb5f4a49bf1befd114428226",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC3300},
            "location":{
              "x":270,
              "y":1007},
            "size":{
              "width":450,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca4367b4a0f94079857e49287b55fe5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC3300},
                "location":{
                  "x":270,
                  "y":1007},
                "size":{
                  "width":450,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u12.png"}},
{
          "id":"79b0edd577a045b889ddb6affcb6e0f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":141,
              "y":927},
            "size":{
              "width":116,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b3fa86893f436d8e71f30a51e93095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":141,
                  "y":927},
                "size":{
                  "width":116,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03aa2febede54ed29592ebd6e379ba26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":927},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1c255fe28f4c5999b42cc016d9e30a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":927},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源主要产耗、用途/u60.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "acf3766b80c24dc495dc7abd187ffb2a":{
      "scriptId":"u0"},
    "13037d4bc89d48518432bd3f6bcd0edd":{
      "scriptId":"u1"},
    "436004daff634579b2d048778fd19d9f":{
      "scriptId":"u2"},
    "65c9151a4ac14a2b859aa711b1f8e420":{
      "scriptId":"u3"},
    "405f36e3e3934c7f9799591af6870fb9":{
      "scriptId":"u4"},
    "ca49ebced9a44f7a906bcb9c8c6e6e78":{
      "scriptId":"u5"},
    "474c31905c124ffda00d125cdc0b60f2":{
      "scriptId":"u6"},
    "80dbc8a7fb1747dc83556d08892cc1f7":{
      "scriptId":"u7"},
    "71cce88c3baa4cabb51df3dd81b0d4a7":{
      "scriptId":"u8"},
    "e0105f462cff4a75b7e557f4d59b0a1f":{
      "scriptId":"u9"},
    "7574fd5f5705490aa444851a81902890":{
      "scriptId":"u10"},
    "7a0ef121a70344808a638c1da4f96098":{
      "scriptId":"u11"},
    "b154c621a2834d30915bc2bf679ce871":{
      "scriptId":"u12"},
    "496b2e7a0a3c46c2bcdca63ad72c4662":{
      "scriptId":"u13"},
    "4dbd8557960e4e399d0e581d6e12de7d":{
      "scriptId":"u14"},
    "59890839b2a946848357884092ca8a2c":{
      "scriptId":"u15"},
    "45f88b16b3b94b52a8611ec46d0d18f3":{
      "scriptId":"u16"},
    "8f725d6adf154114b55b6c646fba9f68":{
      "scriptId":"u17"},
    "3bf4e66548a548659ee257bbc958c6e6":{
      "scriptId":"u18"},
    "9db6a54a592d42b8852a76bf1781c8d8":{
      "scriptId":"u19"},
    "ca96f6011eb44297a527fa8446b30067":{
      "scriptId":"u20"},
    "5433442ca8ea468ebb783f01f0c52eb7":{
      "scriptId":"u21"},
    "68c46f893bf6431aae315056200f2652":{
      "scriptId":"u22"},
    "318d86b8bf00468e96f0f35845dafcdf":{
      "scriptId":"u23"},
    "c9c12aa082ef4c699be0d05424072217":{
      "scriptId":"u24"},
    "2b660b88e36442c88375fca8761f54bd":{
      "scriptId":"u25"},
    "8ccba779a1f748f6bc5ea5a08a6ad4f7":{
      "scriptId":"u26"},
    "c7bb7af209da4564b8ce3d19bb947158":{
      "scriptId":"u27"},
    "d5d2e43227a0482998a4c13b35ab2b25":{
      "scriptId":"u28"},
    "0eabbc4bfcb14ff6877c9ab997c913c3":{
      "scriptId":"u29"},
    "4d4c4a335d8b4002811fa114b2f3d890":{
      "scriptId":"u30"},
    "f7418c32da104268bd912a8f44784cac":{
      "scriptId":"u31"},
    "73bb856d9f9745b6b453b6fc6a7dcbc3":{
      "scriptId":"u32"},
    "0759d276180740619e34bffe186a9ebb":{
      "scriptId":"u33"},
    "53879477d7bd40e38301ce47f0e2f6c9":{
      "scriptId":"u34"},
    "7056e6597e394d14ba25205e93c1138e":{
      "scriptId":"u35"},
    "033db6a80c284beab561fa8b57d4b74f":{
      "scriptId":"u36"},
    "6a8ae8a3d368448d899e252bfb65a7bd":{
      "scriptId":"u37"},
    "fe8be7c9290a4a20aa257c07afa8f19b":{
      "scriptId":"u38"},
    "2af530231ee8450daac2aff3a88d4e84":{
      "scriptId":"u39"},
    "5b9df5cd03494a3ab7ecc9e80a7d11f2":{
      "scriptId":"u40"},
    "92647ae90d9c49b694390463f5b8c3eb":{
      "scriptId":"u41"},
    "86be97f343fa411f96a490261a8b6621":{
      "scriptId":"u42"},
    "378764eb26ef4929962eb8606593848e":{
      "scriptId":"u43"},
    "a8412d5e393b4f2d9b68e722834dc220":{
      "scriptId":"u44"},
    "4926243c6110421cba28ac26aaa2e10d":{
      "scriptId":"u45"},
    "71b4eb547c5e453a8eb7f1d27a858998":{
      "scriptId":"u46"},
    "9095ed6580af47ee8d4a319569490dfa":{
      "scriptId":"u47"},
    "6c8a78d4cd8f43a280f7930670626902":{
      "scriptId":"u48"},
    "7ddce926cfe14270a733013d44d93f23":{
      "scriptId":"u49"},
    "49038e8c65934d9ab95e633e9c166168":{
      "scriptId":"u50"},
    "6d881ab948984838a5f307f8c3e97fff":{
      "scriptId":"u51"},
    "9515abc941674be594cb52b4a92cb48e":{
      "scriptId":"u52"},
    "85b820a64220472abc439b73628d5efe":{
      "scriptId":"u53"},
    "8fe9a565174e494f95f7c104caf294a3":{
      "scriptId":"u54"},
    "375c908c76c046389dd3a630cd0f9001":{
      "scriptId":"u55"},
    "16e20eaacb5f4a49bf1befd114428226":{
      "scriptId":"u56"},
    "ca4367b4a0f94079857e49287b55fe5b":{
      "scriptId":"u57"},
    "79b0edd577a045b889ddb6affcb6e0f1":{
      "scriptId":"u58"},
    "29b3fa86893f436d8e71f30a51e93095":{
      "scriptId":"u59"},
    "03aa2febede54ed29592ebd6e379ba26":{
      "scriptId":"u60"},
    "8b1c255fe28f4c5999b42cc016d9e30a":{
      "scriptId":"u61"}}});