$axure.loadCurrentPage({
  "url":"店铺.html",
  "generationDate":new Date(1509955837680.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1621df5c591b4a0b94617a926b6872ba",
    "type":"Axure:Page",
    "name":"店铺",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3287be110bf144fbbe628177b8539ca0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf284115fc884466971ceffe2c206168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":40},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"0fca0615c34d41e895aeec6f78961b2b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":320},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"929d4e6e538c4d999880d0ec961263e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":320},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"0e334c803bdb47328871aab4da15f545",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":180},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3b4a1d16ef2466da9e4c62bcfaea3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":180},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"70649d622e334bb3a25c10b805992e48",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":190,
              "y":100},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"552f93e630b840bd8dee5cbf48d512ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":100},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"5807ea77b1ea4a83882d7d6315dc56a0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":190,
              "y":240},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59faa705f49048baab021215f0373223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":240},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"0775874181544533b8f42497b482c2a4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":190,
              "y":240},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cced410d0964ce7b6c58310defafbb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":240},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"abc53c2125bb41fdbc20e29b6a822dd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":350,
              "y":34},
            "size":{
              "width":230,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e26e6abaf3f4ddf8c53d41fc4ea715c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":34},
                "size":{
                  "width":230,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3287be110bf144fbbe628177b8539ca0":{
      "scriptId":"u0"},
    "bf284115fc884466971ceffe2c206168":{
      "scriptId":"u1"},
    "0fca0615c34d41e895aeec6f78961b2b":{
      "scriptId":"u2"},
    "929d4e6e538c4d999880d0ec961263e3":{
      "scriptId":"u3"},
    "0e334c803bdb47328871aab4da15f545":{
      "scriptId":"u4"},
    "c3b4a1d16ef2466da9e4c62bcfaea3b8":{
      "scriptId":"u5"},
    "70649d622e334bb3a25c10b805992e48":{
      "scriptId":"u6"},
    "552f93e630b840bd8dee5cbf48d512ba":{
      "scriptId":"u7"},
    "5807ea77b1ea4a83882d7d6315dc56a0":{
      "scriptId":"u8"},
    "59faa705f49048baab021215f0373223":{
      "scriptId":"u9"},
    "0775874181544533b8f42497b482c2a4":{
      "scriptId":"u10"},
    "7cced410d0964ce7b6c58310defafbb2":{
      "scriptId":"u11"},
    "abc53c2125bb41fdbc20e29b6a822dd3":{
      "scriptId":"u12"},
    "3e26e6abaf3f4ddf8c53d41fc4ea715c":{
      "scriptId":"u13"}}});