$axure.loadCurrentPage({
  "url":"掠夺.html",
  "generationDate":new Date(1509955837784.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"575d7931cec64aa3b87a8244303d39aa",
    "type":"Axure:Page",
    "name":"掠夺",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4186ea6ff6234cbebdc9b7541067de99",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a52e4be6adc4b1e9c0a313f10558296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"02a2d8e10006498d9516c74bd2bf2793",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":300},
            "size":{
              "width":160,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c50bb0757e34537b6208710e3a95ac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":300},
                "size":{
                  "width":160,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u2.png"}},
{
          "id":"11d3023406a74e4bb7428ef4311765d3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":160},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1d72a04f874d309b7346ca2f414a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":160},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"be4426a91b1a4a62a79179f853df9095",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":370},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b1fb65291d3474ca8e2b0b8073e112f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":370},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"a1128cb3aac34f46a75876ed9fbe0d11",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":100,
              "y":80},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35aebb9652d340a3b141d80d85f8819d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":80},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"bff52c1d63f349c39311d48c60851c6f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":100,
              "y":220},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff253b93e1b4419995ed197c64871b4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":220},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"979db7ff51194f0b9ef938895ea40cf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":430,
              "y":20},
            "size":{
              "width":140,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f7ff570204f4142a54c41941412354a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":20},
                "size":{
                  "width":140,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf82c7a5c2e340928b25dd51f2e9e549",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":60},
            "size":{
              "width":72,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f65dc21628d4c3cba5f74035c489879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":196,
                  "y":60},
                "size":{
                  "width":72,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u14.gif"}},
{
          "id":"2aa26144d0d048f1829b92a6d1b1ec95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":88},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f44462d210dc4ba4b9025392995e9674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":88},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u16.png"}},
{
          "id":"63c744c1e78d407d81c4e3491ac8e040",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":182},
            "size":{
              "width":64,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd8d141cb8a34b28bad644586e3ae2b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":182},
                "size":{
                  "width":64,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u18.gif"}},
{
          "id":"c269824e95714a82b97eab4857768427",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":160},
            "size":{
              "width":72,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"519fec9eaef1439aa1962f3fc8484b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":160},
                "size":{
                  "width":72,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u14.gif"}},
{
          "id":"8c75d9bb197a49f08fe7bcb91adf8904",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":188},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d9f7327c1b459d8ae07f26c9c1b02a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":188},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u16.png"}},
{
          "id":"bf19379df4a04a248e31b55ccf9e759c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":82},
            "size":{
              "width":64,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29dc8b68085c46f58bfadefd630a4eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":82},
                "size":{
                  "width":64,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掠夺/u18.gif"}},
{
          "id":"7e05a45b8f004f5f8b6ef75e3b0a2cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":222,
              "y":20},
            "size":{
              "width":135,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aab9027befd3415e8043c677386204fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":222,
                  "y":20},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af6ddc4f81ee49f8a096d876935b6dbb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":370},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b38bf4142864e8999f030e6ce45eb21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":370},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"c92907fcef93442aa47d27a225a7c818",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":150,
              "y":400},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f7a5461a8b448aa838701e1de7cb50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":400},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"2b1aea480dfd43d0a7a8bf0a4747be31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":68,
              "y":320},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"021eba084c3a453588910e4a84f5e08a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":68,
                  "y":320},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6062a1a1c9314a3590e77dbbe675bf37",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":460},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59d79a04b9be45efbe0dad9ec2ab0795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":460},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4186ea6ff6234cbebdc9b7541067de99":{
      "scriptId":"u0"},
    "4a52e4be6adc4b1e9c0a313f10558296":{
      "scriptId":"u1"},
    "02a2d8e10006498d9516c74bd2bf2793":{
      "scriptId":"u2"},
    "8c50bb0757e34537b6208710e3a95ac6":{
      "scriptId":"u3"},
    "11d3023406a74e4bb7428ef4311765d3":{
      "scriptId":"u4"},
    "cb1d72a04f874d309b7346ca2f414a01":{
      "scriptId":"u5"},
    "be4426a91b1a4a62a79179f853df9095":{
      "scriptId":"u6"},
    "6b1fb65291d3474ca8e2b0b8073e112f":{
      "scriptId":"u7"},
    "a1128cb3aac34f46a75876ed9fbe0d11":{
      "scriptId":"u8"},
    "35aebb9652d340a3b141d80d85f8819d":{
      "scriptId":"u9"},
    "bff52c1d63f349c39311d48c60851c6f":{
      "scriptId":"u10"},
    "ff253b93e1b4419995ed197c64871b4c":{
      "scriptId":"u11"},
    "979db7ff51194f0b9ef938895ea40cf6":{
      "scriptId":"u12"},
    "2f7ff570204f4142a54c41941412354a":{
      "scriptId":"u13"},
    "cf82c7a5c2e340928b25dd51f2e9e549":{
      "scriptId":"u14"},
    "8f65dc21628d4c3cba5f74035c489879":{
      "scriptId":"u15"},
    "2aa26144d0d048f1829b92a6d1b1ec95":{
      "scriptId":"u16"},
    "f44462d210dc4ba4b9025392995e9674":{
      "scriptId":"u17"},
    "63c744c1e78d407d81c4e3491ac8e040":{
      "scriptId":"u18"},
    "fd8d141cb8a34b28bad644586e3ae2b0":{
      "scriptId":"u19"},
    "c269824e95714a82b97eab4857768427":{
      "scriptId":"u20"},
    "519fec9eaef1439aa1962f3fc8484b32":{
      "scriptId":"u21"},
    "8c75d9bb197a49f08fe7bcb91adf8904":{
      "scriptId":"u22"},
    "e8d9f7327c1b459d8ae07f26c9c1b02a":{
      "scriptId":"u23"},
    "bf19379df4a04a248e31b55ccf9e759c":{
      "scriptId":"u24"},
    "29dc8b68085c46f58bfadefd630a4eff":{
      "scriptId":"u25"},
    "7e05a45b8f004f5f8b6ef75e3b0a2cb2":{
      "scriptId":"u26"},
    "aab9027befd3415e8043c677386204fb":{
      "scriptId":"u27"},
    "af6ddc4f81ee49f8a096d876935b6dbb":{
      "scriptId":"u28"},
    "1b38bf4142864e8999f030e6ce45eb21":{
      "scriptId":"u29"},
    "c92907fcef93442aa47d27a225a7c818":{
      "scriptId":"u30"},
    "52f7a5461a8b448aa838701e1de7cb50":{
      "scriptId":"u31"},
    "2b1aea480dfd43d0a7a8bf0a4747be31":{
      "scriptId":"u32"},
    "021eba084c3a453588910e4a84f5e08a":{
      "scriptId":"u33"},
    "6062a1a1c9314a3590e77dbbe675bf37":{
      "scriptId":"u34"},
    "59d79a04b9be45efbe0dad9ec2ab0795":{
      "scriptId":"u35"}}});