$axure.loadCurrentPage({
  "url":"魔王.html",
  "generationDate":new Date(1509955837374.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"74ba9fa684c84d5385be4a024a7619e6",
    "type":"Axure:Page",
    "name":"魔王",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9a79c761124442399991fc543272f2b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":680},
            "size":{
              "width":200,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7f532f668842768f11284438aaf8dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":680},
                "size":{
                  "width":200,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u0.png"}},
{
          "id":"e34553f0a28849159b719d0a902882d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":598,
              "y":697},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab497cac6ec04f1e82169882edf0c6ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":598,
                  "y":697},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94ab32b5c8364e3bb3350d617f56e29f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":320},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04dedb60a71a449a8aacd6f88f2e22b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":320},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u4.png"}},
{
          "id":"7b7462e2d7454fcdbd0752855c3c1bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":598,
              "y":334},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73900319ed4245e9af15172f3cc79aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":598,
                  "y":334},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c88c02e6fed4c75bd4cf0a28975d47f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":320},
            "size":{
              "width":200,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d248da6c7bd6478d9bbe3ab1d0eb0a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":320},
                "size":{
                  "width":200,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u8.png"}},
{
          "id":"535f0cd32a3645b681bc9ddc2a26330a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ed6c44f026946d79f68c17a4b9f41d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":40},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"908c23db50b344178b2d974a8bc15f6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":780,
              "y":530},
            "size":{
              "width":390,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e27f39069e3a4abe8dad06e1c8a11efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":780,
                  "y":530},
                "size":{
                  "width":390,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24797309d38742b6b1c444efed7f50fe",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":180},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5187f70a20f4c51bd028b3bc9294474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":180},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"13f902914cbb43c88c21416c13ff9bf5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":390},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094751aaf74142fd87756331aa4f5d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":390},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"a4d3ddbb53b14ad4a4e38498f79a1a48",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":390},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffcd922d1a714805b8cab237e8850f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":390},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"1fff6561825b402bbc0e0c031664de9d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7435c56c20b64deb89c88ab8a729cdbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"58052a645f284bfcb776485f0f697afa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":750},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ab329a291d64b28b1a8f54c6f515b9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":750},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"fa8a05421529493da4841ad73052746a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":750},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b140643ddbdd41cb995471b4b72ce073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":750},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"50adf3dd23a1487cb2056d8ef887d818",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":500,
              "y":100},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a047cf912ce4ac6b089a428f0ec2f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":500,
                  "y":100},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"c0add713ba8843a987497f0048a8b35f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":500,
              "y":240},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45aabd0ea88945db9b26e69e807d5ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":500,
                  "y":240},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"959b7ed2d7144086a054639ecd19d561",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":320},
            "size":{
              "width":200,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f975c7765a4a24a8fb1cacf32402b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":320},
                "size":{
                  "width":200,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u30.png"}},
{
          "id":"3c9169c18bfb48b58e21ef75f44fdd83",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":390},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15ee5ab497547269b7bc37cfe0c9082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":390},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"ade0a2645172437ba66e672bfdde5da7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":660},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb60a84b104047ce8dc3b7ff62a9d0e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":660},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"f67976bb08c74e21afce8c1889ac4359",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":500,
              "y":240},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b4b015d3044ad6b82219a4330fcc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":500,
                  "y":240},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"5b338a96437346db97df6569adf55b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":78,
              "y":334},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dec6089af34c4c99b004e3d1d5348d83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":78,
                  "y":334},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"094cec4fd4ed4c06a1eef3513c179947",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":338,
              "y":334},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97440665e57440769abdd33c9a2806b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":338,
                  "y":334},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b6581baea6045f9a53aa2c71b547da3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":18},
            "size":{
              "width":97,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aa62ade11e84be99af2db43f8131661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":18},
                "size":{
                  "width":97,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u42.gif"}},
{
          "id":"7409fb31620c4725958be2e6afb12259",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":721,
              "y":47},
            "size":{
              "width":97,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e9adba943c424ba70e37ba590bd885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":721,
                  "y":47},
                "size":{
                  "width":97,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u44.gif"}},
{
          "id":"a4cbdc28c1f644bba9e6a4ab33880a84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":843,
              "y":37},
            "size":{
              "width":87,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cd925c7f6044d2f8ce805b13fec9ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":843,
                  "y":37},
                "size":{
                  "width":87,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/魔王/u46.gif"}},
{
          "id":"be1eaa42624c42b2b52c9316c1d59e2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":30,
              "y":26},
            "size":{
              "width":380,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ff16d1bc294b5e92fc812d8d65ef9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":30,
                  "y":26},
                "size":{
                  "width":380,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2e0687855ae4c18b54e1b1838e868e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":990,
              "y":26},
            "size":{
              "width":230,
              "height":204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b775815a6f541d58aa1e40a6e351d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":26},
                "size":{
                  "width":230,
                  "height":204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df36903c892348918820dc76afd31216",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":6,
              "y":770},
            "size":{
              "width":208,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e4e05d06b0d4140b4113cf1c37aa364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":6,
                  "y":770},
                "size":{
                  "width":208,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b0ebcc5045c46b0a64999248eff9e89",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a752a14b921481682927c72cb04ac7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"4855c67eb8224264b0ba408c1f799003",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":570},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f199beb79ff41698cf8fabdf1e3cf8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":570},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"0f98d0871c4b47208c4e30c187e7de15",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":570},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b85c597fff584c4ebedb94f3fd83d79f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":570},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"7562d85f08894b6793c1ebc954404973",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":660},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31033f97261a40e3af31f5b165afc41b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":660},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"5bbde1831a7e431d90c666ba4a5dcb23",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":500,
              "y":240},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0df974d6c7d4fabaa726f16fc660b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":500,
                  "y":240},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"46b3a29a3a0346ab8341ecb5a43fba80",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":420,
              "y":420},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52e397566dfd49d497c9b0aeb91cf4bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":420,
                  "y":420},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"ca861269328949e2ac37cef4faa312bc",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":420},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bae50bbaf3a4b71a69c6206cc18b634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":420},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "d9a79c761124442399991fc543272f2b":{
      "scriptId":"u0"},
    "1d7f532f668842768f11284438aaf8dc":{
      "scriptId":"u1"},
    "e34553f0a28849159b719d0a902882d8":{
      "scriptId":"u2"},
    "ab497cac6ec04f1e82169882edf0c6ff":{
      "scriptId":"u3"},
    "94ab32b5c8364e3bb3350d617f56e29f":{
      "scriptId":"u4"},
    "04dedb60a71a449a8aacd6f88f2e22b4":{
      "scriptId":"u5"},
    "7b7462e2d7454fcdbd0752855c3c1bb3":{
      "scriptId":"u6"},
    "73900319ed4245e9af15172f3cc79aee":{
      "scriptId":"u7"},
    "0c88c02e6fed4c75bd4cf0a28975d47f":{
      "scriptId":"u8"},
    "d248da6c7bd6478d9bbe3ab1d0eb0a0f":{
      "scriptId":"u9"},
    "535f0cd32a3645b681bc9ddc2a26330a":{
      "scriptId":"u10"},
    "2ed6c44f026946d79f68c17a4b9f41d4":{
      "scriptId":"u11"},
    "908c23db50b344178b2d974a8bc15f6a":{
      "scriptId":"u12"},
    "e27f39069e3a4abe8dad06e1c8a11efe":{
      "scriptId":"u13"},
    "24797309d38742b6b1c444efed7f50fe":{
      "scriptId":"u14"},
    "d5187f70a20f4c51bd028b3bc9294474":{
      "scriptId":"u15"},
    "13f902914cbb43c88c21416c13ff9bf5":{
      "scriptId":"u16"},
    "094751aaf74142fd87756331aa4f5d26":{
      "scriptId":"u17"},
    "a4d3ddbb53b14ad4a4e38498f79a1a48":{
      "scriptId":"u18"},
    "ffcd922d1a714805b8cab237e8850f02":{
      "scriptId":"u19"},
    "1fff6561825b402bbc0e0c031664de9d":{
      "scriptId":"u20"},
    "7435c56c20b64deb89c88ab8a729cdbc":{
      "scriptId":"u21"},
    "58052a645f284bfcb776485f0f697afa":{
      "scriptId":"u22"},
    "5ab329a291d64b28b1a8f54c6f515b9e":{
      "scriptId":"u23"},
    "fa8a05421529493da4841ad73052746a":{
      "scriptId":"u24"},
    "b140643ddbdd41cb995471b4b72ce073":{
      "scriptId":"u25"},
    "50adf3dd23a1487cb2056d8ef887d818":{
      "scriptId":"u26"},
    "3a047cf912ce4ac6b089a428f0ec2f14":{
      "scriptId":"u27"},
    "c0add713ba8843a987497f0048a8b35f":{
      "scriptId":"u28"},
    "45aabd0ea88945db9b26e69e807d5ac5":{
      "scriptId":"u29"},
    "959b7ed2d7144086a054639ecd19d561":{
      "scriptId":"u30"},
    "31f975c7765a4a24a8fb1cacf32402b5":{
      "scriptId":"u31"},
    "3c9169c18bfb48b58e21ef75f44fdd83":{
      "scriptId":"u32"},
    "d15ee5ab497547269b7bc37cfe0c9082":{
      "scriptId":"u33"},
    "ade0a2645172437ba66e672bfdde5da7":{
      "scriptId":"u34"},
    "cb60a84b104047ce8dc3b7ff62a9d0e7":{
      "scriptId":"u35"},
    "f67976bb08c74e21afce8c1889ac4359":{
      "scriptId":"u36"},
    "c9b4b015d3044ad6b82219a4330fcc5e":{
      "scriptId":"u37"},
    "5b338a96437346db97df6569adf55b48":{
      "scriptId":"u38"},
    "dec6089af34c4c99b004e3d1d5348d83":{
      "scriptId":"u39"},
    "094cec4fd4ed4c06a1eef3513c179947":{
      "scriptId":"u40"},
    "97440665e57440769abdd33c9a2806b1":{
      "scriptId":"u41"},
    "6b6581baea6045f9a53aa2c71b547da3":{
      "scriptId":"u42"},
    "6aa62ade11e84be99af2db43f8131661":{
      "scriptId":"u43"},
    "7409fb31620c4725958be2e6afb12259":{
      "scriptId":"u44"},
    "26e9adba943c424ba70e37ba590bd885":{
      "scriptId":"u45"},
    "a4cbdc28c1f644bba9e6a4ab33880a84":{
      "scriptId":"u46"},
    "2cd925c7f6044d2f8ce805b13fec9ee9":{
      "scriptId":"u47"},
    "be1eaa42624c42b2b52c9316c1d59e2f":{
      "scriptId":"u48"},
    "e1ff16d1bc294b5e92fc812d8d65ef9d":{
      "scriptId":"u49"},
    "e2e0687855ae4c18b54e1b1838e868e0":{
      "scriptId":"u50"},
    "8b775815a6f541d58aa1e40a6e351d42":{
      "scriptId":"u51"},
    "df36903c892348918820dc76afd31216":{
      "scriptId":"u52"},
    "9e4e05d06b0d4140b4113cf1c37aa364":{
      "scriptId":"u53"},
    "3b0ebcc5045c46b0a64999248eff9e89":{
      "scriptId":"u54"},
    "3a752a14b921481682927c72cb04ac7c":{
      "scriptId":"u55"},
    "4855c67eb8224264b0ba408c1f799003":{
      "scriptId":"u56"},
    "9f199beb79ff41698cf8fabdf1e3cf8d":{
      "scriptId":"u57"},
    "0f98d0871c4b47208c4e30c187e7de15":{
      "scriptId":"u58"},
    "b85c597fff584c4ebedb94f3fd83d79f":{
      "scriptId":"u59"},
    "7562d85f08894b6793c1ebc954404973":{
      "scriptId":"u60"},
    "31033f97261a40e3af31f5b165afc41b":{
      "scriptId":"u61"},
    "5bbde1831a7e431d90c666ba4a5dcb23":{
      "scriptId":"u62"},
    "c0df974d6c7d4fabaa726f16fc660b51":{
      "scriptId":"u63"},
    "46b3a29a3a0346ab8341ecb5a43fba80":{
      "scriptId":"u64"},
    "52e397566dfd49d497c9b0aeb91cf4bd":{
      "scriptId":"u65"},
    "ca861269328949e2ac37cef4faa312bc":{
      "scriptId":"u66"},
    "0bae50bbaf3a4b71a69c6206cc18b634":{
      "scriptId":"u67"}}});