$axure.loadCurrentPage({
  "url":"主框架.html",
  "generationDate":new Date(1509955836779.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9c7661feb2b54dccb134edafb30574e9",
    "type":"Axure:Page",
    "name":"主框架",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d1c92e9b26b4b43bc915e0966205874",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":721,
              "y":960},
            "size":{
              "width":252,
              "height":303},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0399f96a58243738fc5f4b747f983fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":721,
                  "y":960},
                "size":{
                  "width":252,
                  "height":303},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u0.png"}},
{
          "id":"4e5b8aaca6ee466fb1b4dc1b46c44617",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":620},
            "size":{
              "width":252,
              "height":303}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8800474be2d44c0ba44800afa438cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":620},
                "size":{
                  "width":252,
                  "height":303}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u2.png"}},
{
          "id":"64552b6cb41b445d8db85b3f490fc973",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":960},
            "size":{
              "width":252,
              "height":303}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7086a10a41d848dd8102809b89f1c125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":960},
                "size":{
                  "width":252,
                  "height":303}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u2.png"}},
{
          "id":"2f6ee100768546ae9dddde8df06f298e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":815,
              "y":986},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504ee400b6ab44c9a9326375324c6588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":815,
                  "y":986},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31c733e441e74936b11468a77b157077",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":165,
              "y":986},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f28013c3f3147bda491479ce4dac3a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":165,
                  "y":986},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e980ca9f2c274896afc96d55a4c02a24",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":147,
              "y":1056},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7335a8793e0342a98beedae9c4eb1399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":147,
                  "y":1056},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"aaee2e8fb8314471ac76240f2a93ca7d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":147,
              "y":1162},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f91d17d4844b3fa31bda53767687b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":147,
                  "y":1162},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"b0471cc11a8b49e2b57acaec26971e6a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":694},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85d7cf7a31d4531af88afa73bcd8cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":694},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"5f93dada2ed644ba8113f09e3329466d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":797,
              "y":1056},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca7154be65704f55b1443db61ba0b930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":797,
                  "y":1056},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"a3cd502c520541a68c2c92daad6e0e59",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":846},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bb3a724a977453c81fab20b1c610e2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":846},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"f0540988eb074f2a90fe7ae0af1dc2a6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":797,
              "y":1162},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb97d5b51d4341e5a8e903244db6cf7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":797,
                  "y":1162},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"69099bd03ee94bc5b77a403a019aaf7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":499,
              "y":646},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"542c82d6e99a4b77906d32f9aa18c39e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":499,
                  "y":646},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5317fd1ed0ce49afba6a3685d14dd455",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":1082},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa1c610285f4605a63f2bef24410c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":1082},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"c50e12a6c8304b3c945769ab1434469b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":405,
              "y":772},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6889c4ab8bc144919171e1bd45e7de6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":405,
                  "y":772},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"b67c303e52b444e481620623a99c815e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":657,
              "y":772},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c03447e91fc74522b29d74d66440fc9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":657,
                  "y":772},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"222ade98063f4f228f1a71d75125a9de",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":323,
              "y":1112},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d49d66014d3a4f8a8ddde0d9fd0feb74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":323,
                  "y":1112},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"f2154481892f4ccc90520a88392ae4ee",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":721,
              "y":1112},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d99e95b20ba4bfcb7eddea438dda7a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":721,
                  "y":1112},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"d694879f0e4f44b9846365830fc89a6a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3366,
              "opacity":1},
            "location":{
              "x":531,
              "y":1082},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0648968de86409ebb05b3faceaf5d82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "location":{
                  "x":531,
                  "y":1082},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"f51edf1a1bc44f3284f9be501b4310ae",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":1297},
            "size":{
              "width":252,
              "height":303}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4341f335a5f4809beb6d3addbcb579c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":1297},
                "size":{
                  "width":252,
                  "height":303}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u2.png"}},
{
          "id":"544951de78d744ce8b9fab0af5bb2f1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":499,
              "y":1323},
            "size":{
              "width":65,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06da37e151f44604a49f44162662dea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":499,
                  "y":1323},
                "size":{
                  "width":65,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b34254f276a4af3a0a3b3802a28ada1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":1393},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb24ab9e18c42c6a59dde1ca099f477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":1393},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"60106c95945c4660a01e331b57adf5a0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":1499},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4de08d4795354914be5d67ccb710ac79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":1499},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"b1691c667b5745ac86b02426cc4c00e2",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":531,
              "y":1297},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd2b16c5a9043749d4b7a18cf13c021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":531,
                  "y":1297},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"0c44e3e1ac064b4ab72e16393f2f6c89",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":197,
              "y":1263},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc353b2299242e8bf01163ca194f272",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":197,
                  "y":1263},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"08c269ffd41842caa4fc1541ded7fc97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":2114},
            "size":{
              "width":621,
              "height":366}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"740d052d98fb43a0b2e8b544f8c6bf29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":2114},
                "size":{
                  "width":621,
                  "height":366}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u48.jpg"}},
{
          "id":"9fe1d68759074136aee549d096bccff7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":770},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"546a6bb723d44649afa7dabc73aadd09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":770},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"64cb65ded5b1468a8142797404bb843e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":721,
              "y":1200},
            "size":{
              "width":117,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"258e64ae9906491cb880db39c553b954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":721,
                  "y":1200},
                "size":{
                  "width":117,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u52.png"}},
{
          "id":"14ad635597fc4d6c8b41e8553290343a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":1200},
            "size":{
              "width":117,
              "height":131}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad1a572db1c46f68ee56ffb051ea54d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":1200},
                "size":{
                  "width":117,
                  "height":131}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u52.png"}},
{
          "id":"7154874c634143c0815fd2fa0972063b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":156,
              "y":119},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbca2dcd77094bfeaea8a56703406056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":156,
                  "y":119},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u56.png"}},
{
          "id":"4c119ceee5084536828645fef8b0bf69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":422,
              "y":119},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc601bd65b56443abbd1bad877bb448b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":422,
                  "y":119},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u56.png"}},
{
          "id":"053be39bff244f02a2b4657565f041ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":688,
              "y":119},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a9806370d5547eb98a01635ad6e3c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":688,
                  "y":119},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u56.png"}},
{
          "id":"42bd7456695042e1a0d1dac32efa6278",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":156,
              "y":349},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387033a229a34c7faa98ce6fff1b53c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":156,
                  "y":349},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u56.png"}},
{
          "id":"551041c5df8346f38f5e4c8259f22889",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":422,
              "y":349},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a4233cd5814920bf34a65dc1c9f4c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":422,
                  "y":349},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u56.png"}},
{
          "id":"fb8770492fbc4f57bf476c2f9f9f01e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":247,
              "y":25},
            "size":{
              "width":550,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e67287411f47d7b6c8bc4be298b8f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":25},
                "size":{
                  "width":550,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a8f307cd6db47249c100d20bc6c6494",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":859,
              "y":1667},
            "size":{
              "width":231,
              "height":414}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da7d6e01765f43c6b4dfa0f88073650b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":859,
                  "y":1667},
                "size":{
                  "width":231,
                  "height":414}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u68.png"}},
{
          "id":"36a2751e2afd438f9924a481d7979c16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":2114},
            "size":{
              "width":426,
              "height":366}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c3736b4ebf4c0289742ccf065582b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":2114},
                "size":{
                  "width":426,
                  "height":366}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u70.jpg"}},
{
          "id":"f633916095be42109fdbfb24f955331e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":1667},
            "size":{
              "width":286,
              "height":415}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51c3134753944a419a986f92dfba7675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":1667},
                "size":{
                  "width":286,
                  "height":415}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u72.jpg"}},
{
          "id":"07c7888082ac4120927d8c1011ab6e77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":332,
              "y":1665},
            "size":{
              "width":232,
              "height":417}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1bd1cd4ba724d8b89629bba2617c6a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":332,
                  "y":1665},
                "size":{
                  "width":232,
                  "height":417}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u74.jpg"}},
{
          "id":"2edc4ae796854f51b086abf2b46474d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":1665},
            "size":{
              "width":237,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3752b8b30a304fbd864b666b33f3def7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":1665},
                "size":{
                  "width":237,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u76.jpg"}},
{
          "id":"3bce4b8404dd4e9ca8b07bee8d809e98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC6666,
              "opacity":1},
            "location":{
              "x":688,
              "y":349},
            "size":{
              "width":200,
              "height":200},
            "borderWidth":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e674f307d8c40e1b0ffdb363043846b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC6666,
                  "opacity":1},
                "location":{
                  "x":688,
                  "y":349},
                "size":{
                  "width":200,
                  "height":200},
                "borderWidth":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u56.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7d1c92e9b26b4b43bc915e0966205874":{
      "scriptId":"u0"},
    "b0399f96a58243738fc5f4b747f983fc":{
      "scriptId":"u1"},
    "4e5b8aaca6ee466fb1b4dc1b46c44617":{
      "scriptId":"u2"},
    "b8800474be2d44c0ba44800afa438cdd":{
      "scriptId":"u3"},
    "64552b6cb41b445d8db85b3f490fc973":{
      "scriptId":"u4"},
    "7086a10a41d848dd8102809b89f1c125":{
      "scriptId":"u5"},
    "2f6ee100768546ae9dddde8df06f298e":{
      "scriptId":"u6"},
    "504ee400b6ab44c9a9326375324c6588":{
      "scriptId":"u7"},
    "31c733e441e74936b11468a77b157077":{
      "scriptId":"u8"},
    "0f28013c3f3147bda491479ce4dac3a5":{
      "scriptId":"u9"},
    "e980ca9f2c274896afc96d55a4c02a24":{
      "scriptId":"u10"},
    "7335a8793e0342a98beedae9c4eb1399":{
      "scriptId":"u11"},
    "aaee2e8fb8314471ac76240f2a93ca7d":{
      "scriptId":"u12"},
    "61f91d17d4844b3fa31bda53767687b3":{
      "scriptId":"u13"},
    "b0471cc11a8b49e2b57acaec26971e6a":{
      "scriptId":"u14"},
    "f85d7cf7a31d4531af88afa73bcd8cdf":{
      "scriptId":"u15"},
    "5f93dada2ed644ba8113f09e3329466d":{
      "scriptId":"u16"},
    "ca7154be65704f55b1443db61ba0b930":{
      "scriptId":"u17"},
    "a3cd502c520541a68c2c92daad6e0e59":{
      "scriptId":"u18"},
    "9bb3a724a977453c81fab20b1c610e2b":{
      "scriptId":"u19"},
    "f0540988eb074f2a90fe7ae0af1dc2a6":{
      "scriptId":"u20"},
    "fb97d5b51d4341e5a8e903244db6cf7f":{
      "scriptId":"u21"},
    "69099bd03ee94bc5b77a403a019aaf7f":{
      "scriptId":"u22"},
    "542c82d6e99a4b77906d32f9aa18c39e":{
      "scriptId":"u23"},
    "5317fd1ed0ce49afba6a3685d14dd455":{
      "scriptId":"u24"},
    "2aa1c610285f4605a63f2bef24410c5b":{
      "scriptId":"u25"},
    "c50e12a6c8304b3c945769ab1434469b":{
      "scriptId":"u26"},
    "6889c4ab8bc144919171e1bd45e7de6b":{
      "scriptId":"u27"},
    "b67c303e52b444e481620623a99c815e":{
      "scriptId":"u28"},
    "c03447e91fc74522b29d74d66440fc9c":{
      "scriptId":"u29"},
    "222ade98063f4f228f1a71d75125a9de":{
      "scriptId":"u30"},
    "d49d66014d3a4f8a8ddde0d9fd0feb74":{
      "scriptId":"u31"},
    "f2154481892f4ccc90520a88392ae4ee":{
      "scriptId":"u32"},
    "7d99e95b20ba4bfcb7eddea438dda7a7":{
      "scriptId":"u33"},
    "d694879f0e4f44b9846365830fc89a6a":{
      "scriptId":"u34"},
    "b0648968de86409ebb05b3faceaf5d82":{
      "scriptId":"u35"},
    "f51edf1a1bc44f3284f9be501b4310ae":{
      "scriptId":"u36"},
    "f4341f335a5f4809beb6d3addbcb579c":{
      "scriptId":"u37"},
    "544951de78d744ce8b9fab0af5bb2f1e":{
      "scriptId":"u38"},
    "06da37e151f44604a49f44162662dea9":{
      "scriptId":"u39"},
    "0b34254f276a4af3a0a3b3802a28ada1":{
      "scriptId":"u40"},
    "aeb24ab9e18c42c6a59dde1ca099f477":{
      "scriptId":"u41"},
    "60106c95945c4660a01e331b57adf5a0":{
      "scriptId":"u42"},
    "4de08d4795354914be5d67ccb710ac79":{
      "scriptId":"u43"},
    "b1691c667b5745ac86b02426cc4c00e2":{
      "scriptId":"u44"},
    "acd2b16c5a9043749d4b7a18cf13c021":{
      "scriptId":"u45"},
    "0c44e3e1ac064b4ab72e16393f2f6c89":{
      "scriptId":"u46"},
    "1bc353b2299242e8bf01163ca194f272":{
      "scriptId":"u47"},
    "08c269ffd41842caa4fc1541ded7fc97":{
      "scriptId":"u48"},
    "740d052d98fb43a0b2e8b544f8c6bf29":{
      "scriptId":"u49"},
    "9fe1d68759074136aee549d096bccff7":{
      "scriptId":"u50"},
    "546a6bb723d44649afa7dabc73aadd09":{
      "scriptId":"u51"},
    "64cb65ded5b1468a8142797404bb843e":{
      "scriptId":"u52"},
    "258e64ae9906491cb880db39c553b954":{
      "scriptId":"u53"},
    "14ad635597fc4d6c8b41e8553290343a":{
      "scriptId":"u54"},
    "8ad1a572db1c46f68ee56ffb051ea54d":{
      "scriptId":"u55"},
    "7154874c634143c0815fd2fa0972063b":{
      "scriptId":"u56"},
    "cbca2dcd77094bfeaea8a56703406056":{
      "scriptId":"u57"},
    "4c119ceee5084536828645fef8b0bf69":{
      "scriptId":"u58"},
    "fc601bd65b56443abbd1bad877bb448b":{
      "scriptId":"u59"},
    "053be39bff244f02a2b4657565f041ed":{
      "scriptId":"u60"},
    "5a9806370d5547eb98a01635ad6e3c60":{
      "scriptId":"u61"},
    "42bd7456695042e1a0d1dac32efa6278":{
      "scriptId":"u62"},
    "387033a229a34c7faa98ce6fff1b53c9":{
      "scriptId":"u63"},
    "551041c5df8346f38f5e4c8259f22889":{
      "scriptId":"u64"},
    "d5a4233cd5814920bf34a65dc1c9f4c2":{
      "scriptId":"u65"},
    "fb8770492fbc4f57bf476c2f9f9f01e4":{
      "scriptId":"u66"},
    "d3e67287411f47d7b6c8bc4be298b8f0":{
      "scriptId":"u67"},
    "3a8f307cd6db47249c100d20bc6c6494":{
      "scriptId":"u68"},
    "da7d6e01765f43c6b4dfa0f88073650b":{
      "scriptId":"u69"},
    "36a2751e2afd438f9924a481d7979c16":{
      "scriptId":"u70"},
    "16c3736b4ebf4c0289742ccf065582b0":{
      "scriptId":"u71"},
    "f633916095be42109fdbfb24f955331e":{
      "scriptId":"u72"},
    "51c3134753944a419a986f92dfba7675":{
      "scriptId":"u73"},
    "07c7888082ac4120927d8c1011ab6e77":{
      "scriptId":"u74"},
    "b1bd1cd4ba724d8b89629bba2617c6a6":{
      "scriptId":"u75"},
    "2edc4ae796854f51b086abf2b46474d9":{
      "scriptId":"u76"},
    "3752b8b30a304fbd864b666b33f3def7":{
      "scriptId":"u77"},
    "3bce4b8404dd4e9ca8b07bee8d809e98":{
      "scriptId":"u78"},
    "4e674f307d8c40e1b0ffdb363043846b":{
      "scriptId":"u79"}}});