$axure.loadCurrentPage({
  "url":"主结构_1.html",
  "generationDate":new Date(1509955837242.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"07419e523c9342f5a0cb7fe6e1762184",
    "type":"Axure:Page",
    "name":"主结构",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b0471cc11a8b49e2b57acaec26971e6a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":40},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85d7cf7a31d4531af88afa73bcd8cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":40},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"1ebda89577c94b669bed8be2a8c49bfe",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":240},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9782e3828b2a4e50a402313fe8446efc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":240},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"1c275f5315874b46944a705db0fe01f5",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":250,
              "y":100},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c86c6e6ca574ca38b783b23f489a5f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":100},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"8d197f1d4ae540958f308f5acdc2ecbb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a71ce04913ee463dba4119d4578477a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"9ce94953c0aa4e8b82f712f3c61aeed6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":250,
              "y":100},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffb7694caae443a293ddbdb18bd08a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":100},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]},
{
          "id":"ae0b817f34cc47a99361c9e6fc26c503",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":240},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8fbde32aec1436581a27e5fcc3aaa9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":240},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"540413cf03e841d7a5402e2bb03d2ede",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":250,
              "y":100},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f7c7d4356e74bed988789250c5f7069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":100},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "b0471cc11a8b49e2b57acaec26971e6a":{
      "scriptId":"u0"},
    "f85d7cf7a31d4531af88afa73bcd8cdf":{
      "scriptId":"u1"},
    "1ebda89577c94b669bed8be2a8c49bfe":{
      "scriptId":"u2"},
    "9782e3828b2a4e50a402313fe8446efc":{
      "scriptId":"u3"},
    "1c275f5315874b46944a705db0fe01f5":{
      "scriptId":"u4"},
    "9c86c6e6ca574ca38b783b23f489a5f7":{
      "scriptId":"u5"},
    "8d197f1d4ae540958f308f5acdc2ecbb":{
      "scriptId":"u6"},
    "a71ce04913ee463dba4119d4578477a5":{
      "scriptId":"u7"},
    "9ce94953c0aa4e8b82f712f3c61aeed6":{
      "scriptId":"u8"},
    "ffb7694caae443a293ddbdb18bd08a5f":{
      "scriptId":"u9"},
    "ae0b817f34cc47a99361c9e6fc26c503":{
      "scriptId":"u10"},
    "e8fbde32aec1436581a27e5fcc3aaa9f":{
      "scriptId":"u11"},
    "540413cf03e841d7a5402e2bb03d2ede":{
      "scriptId":"u12"},
    "3f7c7d4356e74bed988789250c5f7069":{
      "scriptId":"u13"}}});