$axure.loadCurrentPage({
  "url":"祭坛.html",
  "generationDate":new Date(1509955837507.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"190a69c6d1c342879511732fb9ab44c8",
    "type":"Axure:Page",
    "name":"祭坛",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8eb4ebb59b65425cb60f4c031a771a20",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":350},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f8c6120395046df85b0427db331bd78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":350},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"d41a2bc24d894900a80f99a3b41334e2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":60},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c136fa65e9e74555afe4d95fcb101158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":60},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"9eabed1475804a93a99da8be8bbded8f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":200},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6135582d4b476fbecad151f29ba5ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":200},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"d590a003c325442b81ad95e885d13e77",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":270,
              "y":120},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94830fd5f17f484fb5489dcbcbfcae50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":120},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"5571c5b520024f1a8507465bf9535905",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":270,
              "y":260},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98df2dc7e9574f6aa5ad3376bda766ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":260},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}]},
{
          "id":"0f0e304fda424e1697a63c97236a9ca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":630,
              "y":60},
            "size":{
              "width":200,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad7ed070cfdf4f31b93b8bc752bc4fdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":60},
                "size":{
                  "width":200,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80399dc9a5bd4c81891f1d638283d6d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":60},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13d7da2e71bb4115a824542be67d4e09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":60},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u12.png"}},
{
          "id":"3517de04e7f943faa45afffbac6b3bbb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd66cc9845034ab2a999c2e429318907",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":130},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u14.png"}},
{
          "id":"be77ef9e8f8747848d2bfbaffb04ff81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":130},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8405a64afc2b41f795f33a61e5ef33e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":130},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u16.png"}},
{
          "id":"7d94759813904521b752cdb602f44fe8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":200},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82f364b64f65402d92df4a5de25953ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":200},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u18.png"}},
{
          "id":"e8b381850ae64256b241f9cc34d2208d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":200},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c864c468b5d64a6fae229abe54a1e9e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":200},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u20.png"}},
{
          "id":"46843fcea665453aac94dbec33b07f0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":275},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b531bff37554446b0af127f2d08b0be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":275},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u22.png"}},
{
          "id":"df789cc854c1476a9abdecb89ba5f2a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":275},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a73a9d167e948fc836a1507d8eb88ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":275},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/祭坛/u24.png"}},
{
          "id":"6155eba238e54fa0a194c7f1693f6bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":190,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"575418e8ae7e4e86a7c038f6dbc7b640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":10,
                  "y":20},
                "size":{
                  "width":190,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"990af665601948748ff3e89a17aafeff",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":350},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea982ddb52a0461a85c776ba7a4ee9d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":350},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主框架/u10.png"}},
{
          "id":"7d21c19a31954b47940d12103cbb32ff",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":120,
              "y":380},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d606cc3d0c459381064a5625adb7be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":380},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "8eb4ebb59b65425cb60f4c031a771a20":{
      "scriptId":"u0"},
    "4f8c6120395046df85b0427db331bd78":{
      "scriptId":"u1"},
    "d41a2bc24d894900a80f99a3b41334e2":{
      "scriptId":"u2"},
    "c136fa65e9e74555afe4d95fcb101158":{
      "scriptId":"u3"},
    "9eabed1475804a93a99da8be8bbded8f":{
      "scriptId":"u4"},
    "cc6135582d4b476fbecad151f29ba5ad":{
      "scriptId":"u5"},
    "d590a003c325442b81ad95e885d13e77":{
      "scriptId":"u6"},
    "94830fd5f17f484fb5489dcbcbfcae50":{
      "scriptId":"u7"},
    "5571c5b520024f1a8507465bf9535905":{
      "scriptId":"u8"},
    "98df2dc7e9574f6aa5ad3376bda766ed":{
      "scriptId":"u9"},
    "0f0e304fda424e1697a63c97236a9ca4":{
      "scriptId":"u10"},
    "ad7ed070cfdf4f31b93b8bc752bc4fdc":{
      "scriptId":"u11"},
    "80399dc9a5bd4c81891f1d638283d6d9":{
      "scriptId":"u12"},
    "13d7da2e71bb4115a824542be67d4e09":{
      "scriptId":"u13"},
    "3517de04e7f943faa45afffbac6b3bbb":{
      "scriptId":"u14"},
    "fd66cc9845034ab2a999c2e429318907":{
      "scriptId":"u15"},
    "be77ef9e8f8747848d2bfbaffb04ff81":{
      "scriptId":"u16"},
    "8405a64afc2b41f795f33a61e5ef33e3":{
      "scriptId":"u17"},
    "7d94759813904521b752cdb602f44fe8":{
      "scriptId":"u18"},
    "82f364b64f65402d92df4a5de25953ab":{
      "scriptId":"u19"},
    "e8b381850ae64256b241f9cc34d2208d":{
      "scriptId":"u20"},
    "c864c468b5d64a6fae229abe54a1e9e5":{
      "scriptId":"u21"},
    "46843fcea665453aac94dbec33b07f0a":{
      "scriptId":"u22"},
    "9b531bff37554446b0af127f2d08b0be":{
      "scriptId":"u23"},
    "df789cc854c1476a9abdecb89ba5f2a7":{
      "scriptId":"u24"},
    "8a73a9d167e948fc836a1507d8eb88ea":{
      "scriptId":"u25"},
    "6155eba238e54fa0a194c7f1693f6bb3":{
      "scriptId":"u26"},
    "575418e8ae7e4e86a7c038f6dbc7b640":{
      "scriptId":"u27"},
    "990af665601948748ff3e89a17aafeff":{
      "scriptId":"u28"},
    "ea982ddb52a0461a85c776ba7a4ee9d8":{
      "scriptId":"u29"},
    "7d21c19a31954b47940d12103cbb32ff":{
      "scriptId":"u30"},
    "00d606cc3d0c459381064a5625adb7be":{
      "scriptId":"u31"}}});